### ISSUE TITLE
Add diceroller response

### ISSUE THREAD

**Issue by jacebenson** [jacebenson/cajunbot#20]

**Comment by earlduque** [comment]
for reference: https://github.com/earlduque/SlackOff-Bot/blob/master/update/sys_script_7ee284024f7d6300c8b501b18110c7bd.xml

**Comment by jacebenson** [comment]
I think I might go with this instead;
https://chancejs.com/

**Comment by jacebenson** [comment]
Added a listener for #d4,6,8,10,12,20,30,100
https://github.com/jacebenson/cajunbot/blob/master/responses/chance.js
